### PR TITLE
Jf/delete many

### PR DESCRIPTION
**Pull request by gnulnx**
Not sure of the protocol here.  
Do I need to run tests before submitting a PR?

### CODE REVIEW

**Comment by sebleier** [comment]
@gnulnx – [travis-ci](https://travis-ci.org/sebleier/django-redis-cache/builds/74973244) will run the test suite for every pull request.  It would be nice to include a test to show that if the list is empty that no error is raised, but since the change is fairly trivial I'll just merge once the test suite passes.

Thanks for the patch!

**Comment by gnulnx** [comment]
Added a test and pushed.   As an aside how should we run the tests locally?

**Comment by sebleier** [comment]
@gnulnx – On the root of the repository, run: `make test`

**Comment by sebleier** [comment]
One last thing, can you merge master into your branch to fix the merge conflict?  It should be a fairly straightforward change to the authors file.  Let me know if you need help.

**Comment by gnulnx** [comment]
Thanks @sebleier.   Master has been merged in and all tests pass locally as well.

**Comment by sebleier** [comment]
@gnulnx –Thanks, patched merge and 1.6.1 uploaded to PyPI.

**Comment by gnulnx** [comment]
Thanks @sebleier!   Any idea when it will be ready from PyPi?

**Pull request merged**
