### PR TITLE
Pin redis version to 2.10.6

### PR DESCRIPTION
**Pull request by drgarcia1986**
To avoid some troubles with Redis [3.x series](https://github.com/andymccurdy/redis-py#upgrading-from-redis-py-2x-to-30)

### CODE REVIEW

**Comment by rafaelgotts** [comment]
Hey, i think you forgot [this line](https://github.com/sebleier/django-redis-cache/blob/master/setup.py#L12)

**Comment by drgarcia1986** [comment]
oh man, you're right 👍 
fixed ✅

**Comment by sebleier** [comment]
Thanks! Merged and uploaded to PyPI as version 1.8.1

**Comment by drgarcia1986** [comment]
you're welcome!

**Comment by andialbrecht** [comment]
Thanks!!

Am Do., 15. Nov. 2018, 19:05 hat Diego Garcia <notifications@github.com>
geschrieben:

**Comment by StevenMedina** [comment]
Hi, Means that redis cache will not work with versions higher than 2.10.16? I have redis 3.0.0.post1

**Comment by sebleier** [comment]
I don't think everyone's going to be satisfied with this change.  Some people are going to be using redis > 3.0, but the vast majority are going to be using  < 3.0.  I will either add a compatibility layer to bridge the two versions of cut a major release and pin each version to the compatible redis-py version.

**Comment by StevenMedina** [comment]
@sebleier Great, thanks

**Pull request merged**
