### PR TITLE
Update import of importlib

### LINKED ISSUE #93: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
Seeing this warning on django-redis-cache 1.5.3:

    .../site-packages/redis_cache/utils.py:4: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
     from django.utils.importlib import import_module

### PR DESCRIPTION
**Pull request by carltongibson**
Work around `RemovedInDjango19Warning`. Fixes #93

### CODE REVIEW

**Comment by sebleier** [comment]
There are some testing [errors](https://travis-ci.org/sebleier/django-redis-cache/builds/74118320).  Once those are fixed I'll merge.  Thanks

**Comment by carltongibson** [comment]
Argh! I was caught by the GitHub web UI — great, that I wouldn't have opened the PR without it, not so great, in that there's no way to run you code. 

Should be fixed now.

**Comment by sebleier** [comment]
@carltongibson – Thanks for the patch!  PyPI is updated with version 1.5.4

**Comment by carltongibson** [comment]
@sebleier — no problem. Thank you! (And thanks for the prompt push to PyPI!)

**Pull request merged**
