### PR TITLE
Unstable

### PR DESCRIPTION
**Pull request by sebleier**

### CODE REVIEW

**Comment by stantonk** [comment]
fyi this just started causing errors after a chef_client run updated the requirements.txt to the latest commit :)

**Comment by stantonk** [comment]
```
File "/home/api/api/lib/python2.7/site-packages/django/core/cache/__init__.py", line 57, in get_cache
File "/home/api/api/lib/python2.7/site-packages/django/core/cache/__init__.py", line 87, in _create_cache
```

django.core.cache.backends.base:InvalidCacheBackendError

On Django 1.8.3

**Comment by stantonk** [comment]
our bad for not specifying a commit hash in the requirements.txt file of course, but d'ohhhhhhhhhh :)

**Comment by sebleier** [comment]
@stantonk do you have any other information about why django's raising that exception?  All tests are passing on [Travis-ci](https://travis-ci.org/sebleier/django-redis-cache) so I'm driving blind.

**Comment by stantonk** [comment]
@sebleier it happens right when you call ```get_cache('redis')``` when you use ```django.core.cache.get_cache```, assuming 'redis' is a configured redis backend cache in your settings.py like so:

```
CACHES = {
    'redis': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': 'hostname-redacted:6379',
        'KEY_FUNCTION': 'commons.caching.make_key_plain',
        'OPTIONS': {
            'DB': 0,
```

even just running a ```./manage.py shell``` and executing these two lines fails:

**Comment by sebleier** [comment]
@stantonk thanks for the info, I'll try and reproduce it.

**Comment by stantonk** [comment]
@sebleier happy to help. FYI this is how i fixed it:
```
--e git://github.com/sebleier/django-redis-cache.git#egg=django-redis-cache
+-e git://github.com/sebleier/django-redis-cache.git@0b3b7d0afac3280ab32ad62246141ac97a4cc4eb#egg=django_redis_cache-master
```

**Comment by sebleier** [comment]
@stantonk – 

Hmm, I setup a virtualenv and test django 1.8 project using the following settings for a cache:

```python 
CACHES = {
    'default': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': 'localhost:6379',
        'OPTIONS': {
            'DB': 0,
        }
    },
    'redis': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': 'localhost:6379',
        'OPTIONS': {
            'DB': 0,
        }
    }
}
```
I didn't use a custom key function, because I wouldn't have changed for you between versions.
I opened a shell and imported the cache:

```python
from django.core.cache import get_cache
cache = get_cache('redis')
cache.set('a', 'a')
assert cache.get('a') == 'a'
```

Is there any more information or clues you can provide?

**Comment by sebleier** [comment]
@stantonk – I didn't see the rest of your comment above.  Are you locked into an older version of redis-py?  I just updated the setup.py and requirements file to reflect the new requirement.

**Comment by stantonk** [comment]
@sebleier we are pegged to ```redis==2.4.11```

**Pull request merged**
